version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
