version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"
    REPO_NAME: "spring-microservices"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Build started on `date`

  build:
    commands:
      - echo Building Docker images...
      - docker-compose -f docker-compose.yml build

  post_build:
    commands:
      - echo Build completed on `date`
      # Optional: push to ECR if needed
      # - docker tag your-image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/your-repo:latest
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/your-repo:latest
artifacts:
  files:
    - '**/*'
