version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 026090550003.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker images with docker-compose...
      - docker-compose build

  post_build:
    commands:
      - echo Pushing images to Amazon ECR...
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/eureka-server
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/api-gateway
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/order-service
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/product-service
      - docker push 026090550003.dkr.ecr.us-east-1.amazonaws.com/customer-service

artifacts:
  files:
    - '**/*'
