version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_WAITTIMEINMSWHENSYNCEMPTY=0

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - mongodb
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/orderdb

  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mongodb
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/productdb

  customer-service:
    build:
      context: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mongodb
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/customerdb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
