version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017

  eureka-server:
    image: eurekaserver
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - mongo

  api-gateway:
    image: apigateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server

  customer-service:
    image: customerservice
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mongo

  product-service:
    image: productservice
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mongo

  order-service:
    image: orderservice
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - mongo
