server:
  port: 8088

spring:
  application:
    name: api-gateway

zuul:
  routes:
    customer-service:
      path: /customers/**
      serviceId: customer-service
    product-service:
      path: /products/**
      serviceId: product-service
    order-service:
      path: /orders/**
      serviceId: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  discovery:
    enabled: true
