server:
  port: 8083

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
