server:
  port: 8082

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/productdb?ssl=false&authSource=admin&authMechanism=SCRAM-SHA-1
      authentication-database: admin
      database: productdb
      username: rootuser
      password: rootpass
      host: localhost
      port: 27017

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true