server:
  port: 8082

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017/productdb
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: productdb
      port: 27017
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true