version: '3.8'

services:
  customer-service:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mongodb
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/customerdb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
